#   port mappings
#
#   service         local -> host
#   ------------------------------
#   mongo           27017 -> 8083
#   mongo-express   8081  -> 8082
#   api             5000  -> 8081
#   web             3000  -> 8080

version: '3.3'
services:
  mongo:
    image: mongo:5.0-focal
    ports:
      - '8083:27017'
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    restart: 'no'
  mongo-express:
    image: mongo-express
    ports:
      - '8082:8081'
    depends_on:
      - mongo
    restart: 'no'
  api:
    links:
      - mongo
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
      - api-node-modules:/app/node_modules
    environment:
      NODE_ENV: 'developement'
      HOST: '0.0.0.0'
      PORT: 5000
      RATE_LIMIT_WINDOW_MS: 60000
      RATE_LIMIT_MAX: 100
      RUN_JOBS_STARTUP: 'true'
      MONGO_URI: 'mongodb://mongo:27017/dizzy'
      ES_URI: 'http://es.cibr.qcri.org'
      ES_PING_TIMEOUT_MS: 20000
      ES_CRAWLER_INDEX: 'darkweb-tor-index'
      ES_OLD_CRAWLER_SIZE: 48107548
      ES_RECRAWLER_INDEX: 'darkweb-tor-recrawler-index'
      JWT_SECRET: 'UJl5Y8nK7b7TNjz8'
      JWT_AUTH_EXPIRE_DAYS: '30d'
      JWT_ACTIVATION_EXPIRE_DAYS: '3d'
      JWT_COOKIE_EXPIRE_MS: 259200000
      LOGOUT_COOKIE_EXPIRE_MS: 10000
      RESET_PASSWORD_EXPIRE_MS: 600000
      ACCOUNT_ACTIVIATION_URL: 'http://localhost:8080/activate'
      ACCOUNT_ACTIVIATION_EXPIRE_MS: 259200000
      SEARCH_ALERTS_URL: 'http://localhost:8080/alerts'
      SEARCH_WEB_URL: 'http://localhost:8080/search/web'
      SMTP_HOST: 'smtp.mailtrap.io'
      SMTP_PORT: 2525
      SMTP_EMAIL: '8258c23ad8ff6c'
      SMTP_PASSWORD: '1d76a9fb7b31ed'
      FROM_EMAIL: 'noreply@mail.cibr.qcri.org'
      FROM_NAME: 'Dizzy'
    ports:
      - '8081:5000'
    restart: 'no'
  web:
    depends_on:
      - api
    stdin_open: true
    build:
      context: ./web
      dockerfile: Dockerfile.dev
      args:
        - REACT_APP_AMPLITUDE_API_KEY=${AMPLITUDE_DEV_API_KEY}
    volumes:
      - ./web:/app
      - web-node-modules:/app/node_modules
    environment:
      NODE_ENV: 'developement'
    ports:
      - '8080:3000'
    restart: 'no'

volumes:
  mongo-data:
  mongo-config:
  api-node-modules:
  web-node-modules:
